// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "@prisma/config"; // Added the @ symbol

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     directory: "prisma/migrations", // Note: Some versions use 'directory' instead of 'path'
//   },
//   datasource: {
//     url: process.env.DATABASE_URL,
//     directUrl: process.env.DIRECT_URL,
//   },
// });

import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
